### ISSUE TITLE
채팅 입력시 input에 글자색 안보이는 이슈

### ISSUE THREAD

**Issue by HongJungKim-dev** [jukangpark/Deskify#48]
**Describe the bug**

채팅시 입력하는 도중에 글자가 안보여서 어려움이 있음

**To Reproduce**

1. Click on'messages' menu tab
2. Go to 'chat room'
3. type text

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/7d7700a1-c96a-4e5f-81ca-dfb640362422)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] mac
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jukangpark** [comment]
Good issue

**Comment by HongJungKim-dev** [comment]
해당 내용 해결된것 같아서 closed 하겠습니다.
