### ISSUE TITLE
[버그] 모바일에서 댓글의 프로필 터치시 프로필이 아닌 404

### ISSUE THREAD

**Issue by HongJungKim-dev** [jukangpark/Deskify#56]
**Describe the bug**
모바일에서 댓글의 프로필 터치시 프로필이 아닌 404페이지로 이동

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jukangpark** [comment]
카톡에 사용자 프로필 이미지가 등록안된 경우에, 디폴트 이미지로 렌더링하는 부분 추가해야겠네요. 
ㅋㅋ

**Comment by jukangpark** [comment]
버그픽스 완료
