### ISSUE TITLE
[버그] 디바이스 시스템이 화이트 모드일 경우 Input 태그에 흰 배경 버그,,

### ISSUE THREAD

**Issue by jukangpark** [jukangpark/Deskify#58]
**Describe the bug**
디바이스 시스템이 화이트 모드일때, Input 창의 백그라운드와 color 색상이 화이트인 버그

**To Reproduce**

댓글 Input, 채팅 Input

**Expected behavior**

**Screenshots**
![KakaoTalk_Photo_2024-09-15-14-47-56](https://github.com/user-attachments/assets/0d4f78a5-4db7-48a3-8cb2-a23da238c69d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jukangpark** [comment]
### before

![image](https://github.com/user-attachments/assets/326fd609-4346-436f-ae67-8c2227f0926f)

![image](https://github.com/user-attachments/assets/7c0464bc-9a18-4ff2-94ae-eb235c2150e7)

![image](https://github.com/user-attachments/assets/2617b30d-8d2b-49fe-a925-d10ba049e63a)

**Comment by jukangpark** [comment]
### after


![image](https://github.com/user-attachments/assets/e1d0e761-f766-4335-a2cb-07bd77b5784b)

![image](https://github.com/user-attachments/assets/b604f53b-1890-431f-90e1-259b23c06154)

![image](https://github.com/user-attachments/assets/56245d32-9d7a-44ee-98cf-a7c45dfab2aa)

**Comment by jukangpark** [comment]
tailwindcss 에서 dark: 하고 스타일 속성 주게 되면, 해당 디바이스 시스템 다크 / 라이트 모드 따라가기 때문에, 
dark: 전부 지우고, 설정해주었음

**Comment by HongJungKim-dev** [comment]
https://github.com/jukangpark/Deskify/commit/917911c20120fd2a1ef6b1ab4d5ec657ab194266

해당 커밋으로 해결된것같은데

이 부분 closed하면 될까요?

**Comment by jukangpark** [comment]
넵 제가 close 할게욥
